global using api.Settings;
global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using Microsoft.AspNetCore.Mvc;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using System.ComponentModel.DataAnnotations;
global using api.DTOs;
global using api.Models.Accounts;
